title: Manjil Neupane | Cybersecurity Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  Deutschsprachiges Cybersecurity-Portfolio mit Analysen zu Malware, Digital Forensics, Labs und CTF-Writeups.

author:
  name: "Manjil"
  email: "someone@somewebsite.somedomain"

baseurl: /
source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
  - jekyll-paginate


owner : "Manjil Neupane"
year : "2026"


#For CyberDen
collections:
  cyberden:
    output: true
    permalink: /cyberden/:title
  notes:
    output: true
    permalink: /notes/:name
  certificates:
    output: true
    permalink: /certificates/:name
  forensics:
    output: true
    permalink: notes/digital-forensics/:title
  flare:
    output: true
    permalink: notes/flare-on/:title
  practicalmalware:
    output: true
    permalink: notes/practicalmalware/:title




